# Generated by Django 5.1.6 on 2025-02-27 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(blank='False', max_length=200, null='False', unique=True, verbose_name='Categoria do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(blank='False', max_length=200, null='False', verbose_name='Nome'),
        ),
    ]
